import asyncio
import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from promptchain.observability import track_routing

if TYPE_CHECKING:
    from promptchain.utils.agent_chain import AgentChain

logger = logging.getLogger(__name__)


@track_routing(extract_decision=True)
async def execute_static_plan_strategy_async(
    agent_chain_instance: "AgentChain", initial_user_input: str
) -> str:
    """Executes a plan of agents generated by the router."""
    if agent_chain_instance.verbose:
        print(f"\n--- Executing Router Strategy: static_plan ---")

    # 1. Get the plan from the router
    agent_chain_instance.logger.log_run({"event": "static_plan_get_plan_start"})
    decision_output: Optional[str] = None
    parsed_decision: Dict[str, Any] = {}
    try:
        if agent_chain_instance.custom_router_function:
            logging.warning(
                "Custom router function used with 'static_plan' strategy. Ensure it returns {'plan': [...], 'initial_input': ...}"
            )
            decision_output = await agent_chain_instance.custom_router_function(
                user_input=initial_user_input,
                history=agent_chain_instance._conversation_history,
                agent_descriptions=agent_chain_instance.agent_descriptions,
            )

            # ✅ NEW (v0.4.2): Capture orchestrator metrics if OrchestratorSupervisor was used
            if (
                hasattr(agent_chain_instance, "orchestrator_supervisor")
                and agent_chain_instance.orchestrator_supervisor
            ):
                orchestrator_metrics = (
                    agent_chain_instance.orchestrator_supervisor.get_last_execution_metrics()
                )
                agent_chain_instance._last_orchestrator_metrics = orchestrator_metrics  # type: ignore[attr-defined]
                if agent_chain_instance.verbose:
                    print(
                        f"  Orchestrator metrics captured: {orchestrator_metrics['reasoning_steps']} reasoning steps, {orchestrator_metrics['tools_called']} tools"
                    )

        elif agent_chain_instance.decision_maker_chain:
            decision_output = (
                await agent_chain_instance.decision_maker_chain.process_prompt_async(
                    initial_user_input
                )
            )
        else:
            raise RuntimeError("No router configured for static_plan strategy.")

        if agent_chain_instance.verbose:
            print(f"  Router Plan Output: {decision_output}")
        parsed_decision = agent_chain_instance._parse_decision(decision_output)

        if (
            not parsed_decision
            or "plan" not in parsed_decision
            or "initial_input" not in parsed_decision
        ):
            error_msg = (
                "Router failed to generate a valid plan for static_plan strategy."
            )
            if agent_chain_instance.verbose:
                print(f"  Error: {error_msg} Router Output: {decision_output}")
            agent_chain_instance.logger.log_run(
                {
                    "event": "static_plan_invalid_plan",
                    "raw_output": decision_output,
                    "parsed": parsed_decision,
                }
            )
            return f"Error: Could not determine execution plan. Router output was: {decision_output or '[Empty]'}"

    except Exception as e:
        error_msg = f"Error getting plan from router: {e}"
        logging.error(error_msg, exc_info=True)
        agent_chain_instance.logger.log_run(
            {"event": "static_plan_router_error", "error": str(e)}
        )
        return f"Sorry, an error occurred while planning the execution: {e}"

    plan: List[str] = parsed_decision["plan"]
    current_input: str = parsed_decision["initial_input"]
    final_response: str = ""

    # ✅ Track plan execution metadata for observability (stored on agent_chain_instance)
    agent_chain_instance._last_plan_metadata = {  # type: ignore[attr-defined]
        "plan": plan,
        "agents_executed": [],
        "current_step": 0,
        "total_steps": len(plan),
        "last_agent": None,
    }

    if agent_chain_instance.verbose:
        print(f"  Executing Plan: {' -> '.join(plan)}")
    agent_chain_instance.logger.log_run(
        {
            "event": "static_plan_execution_start",
            "plan": plan,
            "initial_input_length": len(current_input),
        }
    )

    for i, agent_name in enumerate(plan):
        step_num = i + 1
        if agent_chain_instance.verbose:
            print(f"  Plan Step {step_num}/{len(plan)}: Running agent '{agent_name}'")
        agent_chain_instance.logger.log_run(
            {
                "event": "static_plan_step_start",
                "step": step_num,
                "agent": agent_name,
                "input_length": len(current_input),
            }
        )

        # ✅ Emit orchestration event: Agent starting in multi-agent plan
        agent_chain_instance._emit_orchestration_event(
            "plan_agent_start",
            {
                "step_number": step_num,
                "total_steps": len(plan),
                "agent_name": agent_name,
                "plan": plan,
            },
        )

        if agent_name not in agent_chain_instance.agents:
            final_response = f"Error in plan: Agent '{agent_name}' not found."
            agent_chain_instance.logger.log_run(
                {
                    "event": "static_plan_step_error",
                    "step": step_num,
                    "agent": agent_name,
                    "reason": "Agent not found",
                }
            )
            break

        selected_agent = agent_chain_instance.agents[agent_name]
        agent_response_raw: str = ""
        agent_final_output: Optional[str] = None

        try:
            agent_input_for_this_run = current_input

            # ✅ NEW (v0.4.2): Inject conversation history if configured for this agent
            # Check if this agent should receive history (per-agent config or global setting)
            agent_history_config = agent_chain_instance._agent_history_configs.get(
                agent_name, {}
            )
            should_include_history = agent_history_config.get(
                "enabled", agent_chain_instance.auto_include_history
            )

            if should_include_history:
                # Use per-agent history formatting with custom filters and limits
                formatted_history = agent_chain_instance._format_chat_history_for_agent(
                    agent_name=agent_name,
                    max_tokens=agent_history_config.get("max_tokens"),
                    max_entries=agent_history_config.get("max_entries"),
                    truncation_strategy=agent_history_config.get(
                        "truncation_strategy", "oldest_first"
                    ),
                    include_types=agent_history_config.get("include_types"),
                    exclude_sources=agent_history_config.get("exclude_sources"),
                )

                # Wrap the current input with conversation history context
                agent_input_for_this_run = f"""Conversation History:
---
{formatted_history}
---

Current Task (from previous agent or user): {current_input}"""

                # ✅ Calculate token count for history using tiktoken (v0.4.2 - enhanced observability)
                history_tokens = 0
                try:
                    import tiktoken

                    enc = tiktoken.encoding_for_model("gpt-4")
                    history_tokens = len(enc.encode(formatted_history))
                except ImportError:
                    logging.warning(
                        "tiktoken not available - install with 'pip install tiktoken' for accurate token counting"
                    )
                    history_tokens = -1  # Indicates tiktoken not available
                except Exception as e:
                    logging.warning(f"Error calculating token count: {e}")
                    history_tokens = -1

                # ✅ Track cumulative token count across conversation
                if not hasattr(agent_chain_instance, "_cumulative_history_tokens"):
                    agent_chain_instance._cumulative_history_tokens = 0
                if history_tokens > 0:
                    agent_chain_instance._cumulative_history_tokens += history_tokens

                # ✅ FULL HISTORY VISIBILITY: Display with orange color for easy skipping
                # ANSI color code for orange: \033[38;5;208m
                orange_start = "\033[38;5;208m"
                orange_end = "\033[0m"

                token_display = (
                    f"{history_tokens} tokens"
                    if history_tokens > 0
                    else "tokens unavailable (install tiktoken)"
                )
                cumulative_display = (
                    f" | cumulative: {agent_chain_instance._cumulative_history_tokens}"
                    if history_tokens > 0
                    else ""
                )

                logging.info(
                    f"{orange_start}[HISTORY INJECTED] agent={agent_name} | step={step_num} | {token_display}{cumulative_display}{orange_end}"
                )
                logging.info(f"{orange_start}{'='*80}{orange_end}")
                logging.info(f"{orange_start}[HISTORY START]{orange_end}")
                for line in formatted_history.split("\n"):
                    logging.info(f"{orange_start}{line}{orange_end}")
                logging.info(f"{orange_start}[HISTORY END]{orange_end}")
                logging.info(f"{orange_start}{'='*80}{orange_end}")

                # Also keep verbose mode output for backward compatibility
                if agent_chain_instance.verbose:
                    print(
                        f"    Including history for agent '{agent_name}' in plan step {step_num} ({len(formatted_history)} chars, {token_display})"
                    )

                agent_chain_instance.logger.log_run(
                    {
                        "event": "static_plan_history_injected",
                        "step": step_num,
                        "agent": agent_name,
                        "history_length": len(formatted_history),
                        "history_tokens": history_tokens,
                        "cumulative_history_tokens": (
                            agent_chain_instance._cumulative_history_tokens
                            if history_tokens > 0
                            else -1
                        ),
                        "history_content": formatted_history,
                        "agent_config": agent_history_config,
                    }
                )

            agent_loop_broken = False
            for agent_internal_step in range(agent_chain_instance.max_internal_steps):
                if agent_chain_instance.verbose:
                    print(
                        f"    Agent Internal Step {agent_internal_step + 1}/{agent_chain_instance.max_internal_steps} for '{agent_name}'"
                    )

                agent_response_raw = await selected_agent.process_prompt_async(
                    agent_input_for_this_run
                )

                reroute_prefix = "[REROUTE]"
                final_prefix = "[FINAL]"
                response_stripped = agent_response_raw.strip()

                if response_stripped.startswith(reroute_prefix):
                    next_input_content = response_stripped[
                        len(reroute_prefix) :
                    ].strip()
                    if agent_chain_instance.verbose:
                        print(
                            f"    Agent '{agent_name}' requested internal reroute. Next internal input: {next_input_content[:100]}..."
                        )
                    agent_chain_instance.logger.log_run(
                        {
                            "event": "static_plan_agent_reroute",
                            "plan_step": step_num,
                            "agent": agent_name,
                            "internal_step": agent_internal_step + 1,
                        }
                    )
                    agent_input_for_this_run = next_input_content
                    continue
                elif response_stripped.startswith(final_prefix):
                    final_response = response_stripped[len(final_prefix) :].strip()
                    if agent_chain_instance.verbose:
                        print(
                            f"    Agent '{agent_name}' provided [FINAL] answer. Ending plan execution."
                        )
                    agent_chain_instance.logger.log_run(
                        {
                            "event": "static_plan_agent_final_prefix",
                            "plan_step": step_num,
                            "agent": agent_name,
                            "internal_step": agent_internal_step + 1,
                        }
                    )
                    agent_loop_broken = True
                    break
                else:
                    agent_final_output = agent_response_raw
                    if agent_chain_instance.verbose:
                        print(
                            f"    Agent '{agent_name}' finished its step (no prefix). Output length: {len(agent_final_output)}"
                        )
                    agent_chain_instance.logger.log_run(
                        {
                            "event": "static_plan_agent_step_complete",
                            "plan_step": step_num,
                            "agent": agent_name,
                            "internal_step": agent_internal_step + 1,
                        }
                    )
                    agent_loop_broken = True
                    break

            if (
                not agent_loop_broken
                and agent_internal_step == agent_chain_instance.max_internal_steps - 1
            ):
                logging.warning(
                    f"Agent '{agent_name}' reached max internal steps ({agent_chain_instance.max_internal_steps}) during plan step {step_num}."
                )
                agent_chain_instance.logger.log_run(
                    {
                        "event": "static_plan_agent_max_steps",
                        "plan_step": step_num,
                        "agent": agent_name,
                    }
                )
                agent_final_output = agent_response_raw

            if final_response:
                break

            if agent_final_output is None:
                final_response = f"Error: Agent '{agent_name}' failed to produce an output in step {step_num}."
                agent_chain_instance.logger.log_run(
                    {
                        "event": "static_plan_step_error",
                        "step": step_num,
                        "agent": agent_name,
                        "reason": "No final output from agent",
                    }
                )
                break

            agent_chain_instance.logger.log_run(
                {
                    "event": "static_plan_step_success",
                    "step": step_num,
                    "agent": agent_name,
                    "output_length": len(agent_final_output),
                }
            )

            # ✅ Update plan metadata after successful agent execution
            agent_chain_instance._last_plan_metadata["agents_executed"].append(  # type: ignore[attr-defined]
                agent_name
            )
            agent_chain_instance._last_plan_metadata["current_step"] = step_num  # type: ignore[attr-defined]
            agent_chain_instance._last_plan_metadata["last_agent"] = agent_name  # type: ignore[attr-defined]

            # ✅ Emit orchestration event: Agent completed in multi-agent plan
            agent_chain_instance._emit_orchestration_event(
                "plan_agent_complete",
                {
                    "step_number": step_num,
                    "total_steps": len(plan),
                    "agent_name": agent_name,
                    "output_length": len(agent_final_output),
                    "plan": plan,
                },
            )

            current_input = agent_final_output

        except Exception as e:
            error_msg = (
                f"Error executing agent '{agent_name}' in plan step {step_num}: {e}"
            )
            logging.error(error_msg, exc_info=True)
            agent_chain_instance.logger.log_run(
                {
                    "event": "static_plan_step_error",
                    "step": step_num,
                    "agent": agent_name,
                    "error": str(e),
                }
            )
            final_response = f"Plan failed at step {step_num} ({agent_name}): {e}"
            break

        if final_response:
            break

    if not final_response:
        final_response = current_input
        if not final_response:
            final_response = (
                "[Static plan completed but produced an empty final response.]"
            )
            agent_chain_instance.logger.log_run({"event": "static_plan_empty_response"})

    agent_chain_instance.logger.log_run(
        {
            "event": "static_plan_execution_end",
            "final_response_length": len(final_response),
        }
    )
    return final_response
